.catalog:
  name: "FlowInsight"
  version: "2.4.3-rancher1"
  description: "IPFIX data analytics - record decorating pipeline."
  questions:
    - variable: "router_name"
      label: "Router name"
      description: "Name of the router from which will process the IPFIX stream."
      type: "enum"
      options:
          - "nsw-brwy-pe1"
          - "nsw-rsby-pe1"
          - "nsw-mcqp-pe1"
          - "qld-fvly-pe1"
          - "qld-gdpt-pe1"
          - "qld-sprt-pe1"
          - "sa-adel-pe1"
          - "sa-prka-pe1"
          - "wa-knsg-pe1"
          - "wa-eper-pe1"
          - "act-actn-pe1"
          - "act-dksn-pe1"
          - "vic-nbpk-pe1"
          - "vic-crlt-pe1"
          - "vic-wmlb-pe1"
          - "tas-hbrt-pe1"
          - "tas-hbrt-pe2"
          - "nt-drwn-pe1"
          - "akl-wnpa-pe1"
          - "akl-tkpa-pe1"
          - "pretend-router"
      default: vic-nbpk-pe1
      required: true
    - variable: "router_scale"
      label: "Scale"
      description: "Number of processing instances to use for this router."
      type: "enum"
      options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
      default: 1
      required: true
    - variable: "ip_version"
      label: "IP version"
      description: "Internet protocol version (ipv4 or ipv6)."
      type: "enum"
      options:
          - "ipv4"
          - "ipv6"
      default: "ipv4"
      required: true
flowinsight-farm:
  metadata:
    farm:
      yml:
        router_name: "${router_name}"
        router_scale: "${router_scale}"
        ip_version: "${ip_version}"
